In [2]:
import pandas as pd

In [26]:
data=pd.read_csv("../data/raw/Mall_Customers(dataset3).csv",index_col=0)

In [27]:
data.head()

            Gender  Age  Annual Income (k$)  Spending Score (1-100)
CustomerID
1             Male   19                  15                      39
2             Male   21                  15                      81
3           Female   20                  16                       6
4           Female   23                  16                      77
5           Female   31                  17                      40

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 1 to 200
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Gender                  200 non-null    object
 1   Age                     200 non-null    int64
 2   Annual Income (k$)      200 non-null    int64
 3   Spending Score (1-100)  200 non-null    int64
dtypes: int64(3), object(1)
memory usage: 7.8+ KB

In [38]:
data.describe()

       customerid         age  annual_income  spending_score
count  200.000000  200.000000     200.000000      200.000000
mean   100.500000   38.850000      60.560000       50.200000
std     57.879185   13.969007      26.264721       25.823522
min      1.000000   18.000000      15.000000        1.000000
25%     50.750000   28.750000      41.500000       34.750000
50%    100.500000   36.000000      61.500000       50.000000
75%    150.250000   49.000000      78.000000       73.000000
max    200.000000   70.000000     137.000000       99.000000

In [29]:
data = data.reset_index()
data

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [30]:
#check missing values
data.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [31]:
#check for duplicates
data.duplicated().sum()

np.int64(0)

In [32]:
#cleans column names
data.columns = (data.columns.str.strip().str.lower().str.replace(" ", "_"))

In [33]:
#check data types
data.dtypes

customerid                 int64
gender                    object
age                        int64
annual_income_(k$)         int64
spending_score_(1-100)     int64
dtype: object

In [34]:
#check for constant values in dataset
data.nunique()

customerid                200
gender                      2
age                        51
annual_income_(k$)         64
spending_score_(1-100)     84
dtype: int64

In [35]:
#standardize text values
data['gender'] = data['gender'].str.upper()

In [36]:
#rename columns
data = data.rename(columns={'annual_income_(k$)': 'annual_income','spending_score_(1-100)': 'spending_score'})

In [39]:
data

     customerid  gender  age  annual_income  spending_score
0             1    MALE   19             15              39
1             2    MALE   21             15              81
2             3  FEMALE   20             16               6
3             4  FEMALE   23             16              77
4             5  FEMALE   31             17              40
..          ...     ...  ...            ...             ...
195         196  FEMALE   35            120              79
196         197  FEMALE   45            126              28
197         198    MALE   32            126              74
198         199    MALE   32            137              18
199         200    MALE   30            137              83

[200 rows x 5 columns]

In [40]:
data.to_csv("../data/processed/dataset3_clean.csv",index=False)