## Data Cleaning - Dataset 1
#### 1. Data Loading
#### 2. Data Understanding
#### 3. Handling Missing Values
#### 4. Removing Duplicates
#### 5. Data Cleaning & Standardization
#### 6. Feature Engineering
#### 7. Final Dataset

In [1]:
import pandas as pd

In [3]:
data=pd.read_csv("../data/raw/marketing_campaign(dataset1).csv",sep="\t")
data

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,709,...,5,0,0,0,0,0,0,3,11,0
2236,4001,1946,PhD,Together,64014.0,2,1,10-06-2014,56,406,...,7,0,0,0,1,0,0,3,11,0
2237,7270,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,...,6,0,1,0,0,0,0,3,11,0
2238,8235,1956,Master,Together,69245.0,0,1,24-01-2014,8,428,...,3,0,0,0,0,0,0,3,11,0
2239,9405,1954,PhD,Married,52869.0,1,1,15-10-2012,40,84,...,7,0,0,0,0,0,0,3,11,1

In [4]:
data.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), object(3)
memory usage: 507.6+ KB

In [6]:
data.describe() #income has missing values or null vales

,ID,Year_Birth,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
count,2240.000000,2240.000000,2216.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,...,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.0,2240.0,2240.000000
mean,5592.159821,1968.805804,52247.251354,0.444196,0.506250,49.109375,303.935714,26.302232,166.950000,37.525446,...,5.316518,0.072768,0.074554,0.072768,0.064286,0.013393,0.009375,3.0,11.0,0.149107
std,3246.662198,11.984069,25173.076661,0.538398,0.544538,28.962453,336.597393,39.773434,225.715373,54.628979,...,2.426645,0.259813,0.262728,0.259813,0.245316,0.114976,0.096391,0.0,0.0,0.356274
min,0.000000,1893.000000,1730.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
25%,2828.250000,1959.000000,35303.000000,0.000000,0.000000,24.000000,23.750000,1.000000,16.000000,3.000000,...,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
50%,5458.500000,1970.000000,51381.500000,0.000000,0.000000,49.000000,173.500000,8.000000,67.000000,12.000000,...,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
75%,8427.750000,1977.000000,68522.000000,1.000000,1.000000,74.000000,504.250000,33.000000,232.000000,50.000000,...,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
max,11191.000000,1996.000000,666666.000000,2.000000,2.000000,99.000000,1493.000000,199.000000,1725.000000,259.000000,...,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.0,11.0,1.000000

In [7]:
data.isnull().sum() #income has 24 null vales

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [8]:
#to fix missing values of income
data['Income'].fillna(data['Income'].median(), inplace=True)

C:\Users\majum\AppData\Local\Temp\ipykernel_13776\665183929.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Income'].fillna(data['Income'].median(), inplace=True)

In [9]:
data.isnull().sum() #missing vales handled

ID                     0
Year_Birth             0
Education              0
Marital_Status         0
Income                 0
Kidhome                0
Teenhome               0
Dt_Customer            0
Recency                0
MntWines               0
MntFruits              0
MntMeatProducts        0
MntFishProducts        0
MntSweetProducts       0
MntGoldProds           0
NumDealsPurchases      0
NumWebPurchases        0
NumCatalogPurchases    0
NumStorePurchases      0
NumWebVisitsMonth      0
AcceptedCmp3           0
AcceptedCmp4           0
AcceptedCmp5           0
AcceptedCmp1           0
AcceptedCmp2           0
Complain               0
Z_CostContact          0
Z_Revenue              0
Response               0
dtype: int64

In [10]:
data.duplicated().sum()
data.drop_duplicates(inplace=True)

In [11]:
data['Dt_Customer']=pd.to_datetime(data['Dt_Customer'], dayfirst= True) #convert date

In [12]:
data['Income']=data['Income'].astype(int) #convert numeric

In [13]:
#standardize text data
data['Education']=data['Education'].str.lower().str.strip()
data['Marital_Status']=data['Marital_Status'].str.lower().str.strip()

In [14]:
#fix inconsistent category
data['Marital_Status'].unique()
data['Marital_Status']=data['Marital_Status'].replace({'alone':'single','together':'married','absurd':'single','yolo':'single'})

In [15]:
# remove useless columns
data.nunique()
data.drop(['Z_CostContact','Z_Revenue'],axis=1,inplace=True)

In [16]:
#Feature Engineering
data['age']=2026 -data['Year_Birth']
data['total_children']=data['Kidhome']+data['Teenhome']
data['total_spent'] = ( data['MntWines'] + data['MntFruits'] + data['MntMeatProducts'] + data['MntFishProducts'] + data['MntSweetProducts'] + data['MntGoldProds']
)

In [17]:
#rename columns
data.columns = data.columns.str.lower().str.replace(' ', '_')

In [18]:
#outlier handling
data['income'].describe()
data = data[data['income'] < 600000]

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2239 entries, 0 to 2239
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   2239 non-null   int64
 1   year_birth           2239 non-null   int64
 2   education            2239 non-null   object
 3   marital_status       2239 non-null   object
 4   income               2239 non-null   int64
 5   kidhome              2239 non-null   int64
 6   teenhome             2239 non-null   int64
 7   dt_customer          2239 non-null   datetime64[ns]
 8   recency              2239 non-null   int64
 9   mntwines             2239 non-null   int64
 10  mntfruits            2239 non-null   int64
 11  mntmeatproducts      2239 non-null   int64
 12  mntfishproducts      2239 non-null   int64
 13  mntsweetproducts     2239 non-null   int64
 14  mntgoldprods         2239 non-null   int64
 15  numdealspurchases    2239 non-null   int64
 16  numwebpurchases      2239 non-null   int64
 17  numcatalogpurchases  2239 non-null   int64
 18  numstorepurchases    2239 non-null   int64
 19  numwebvisitsmonth    2239 non-null   int64
 20  acceptedcmp3         2239 non-null   int64
 21  acceptedcmp4         2239 non-null   int64
 22  acceptedcmp5         2239 non-null   int64
 23  acceptedcmp1         2239 non-null   int64
 24  acceptedcmp2         2239 non-null   int64
 25  complain             2239 non-null   int64
 26  response             2239 non-null   int64
 27  age                  2239 non-null   int64
 28  total_children       2239 non-null   int64
 29  total_spent          2239 non-null   int64
dtypes: datetime64[ns](1), int64(27), object(2)
memory usage: 542.3+ KB

In [20]:
data.isnull().sum()

id                     0
year_birth             0
education              0
marital_status         0
income                 0
kidhome                0
teenhome               0
dt_customer            0
recency                0
mntwines               0
mntfruits              0
mntmeatproducts        0
mntfishproducts        0
mntsweetproducts       0
mntgoldprods           0
numdealspurchases      0
numwebpurchases        0
numcatalogpurchases    0
numstorepurchases      0
numwebvisitsmonth      0
acceptedcmp3           0
acceptedcmp4           0
acceptedcmp5           0
acceptedcmp1           0
acceptedcmp2           0
complain               0
response               0
age                    0
total_children         0
total_spent            0
dtype: int64

In [24]:
#Final Dataset
data

,id,year_birth,education,marital_status,income,kidhome,teenhome,dt_customer,recency,mntwines,...,acceptedcmp3,acceptedcmp4,acceptedcmp5,acceptedcmp1,acceptedcmp2,complain,response,age,total_children,total_spent
0,5524,1957,graduation,single,58138,0,0,2012-09-04,58,635,...,0,0,0,0,0,0,1,69,0,1617
1,2174,1954,graduation,single,46344,1,1,2014-03-08,38,11,...,0,0,0,0,0,0,0,72,2,27
2,4141,1965,graduation,married,71613,0,0,2013-08-21,26,426,...,0,0,0,0,0,0,0,61,0,776
3,6182,1984,graduation,married,26646,1,0,2014-02-10,26,11,...,0,0,0,0,0,0,0,42,1,53
4,5324,1981,phd,married,58293,1,0,2014-01-19,94,173,...,0,0,0,0,0,0,0,45,1,422
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,graduation,married,61223,0,1,2013-06-13,46,709,...,0,0,0,0,0,0,0,59,1,1341
2236,4001,1946,phd,married,64014,2,1,2014-06-10,56,406,...,0,0,0,1,0,0,0,80,3,444
2237,7270,1981,graduation,divorced,56981,0,0,2014-01-25,91,908,...,0,1,0,0,0,0,0,45,0,1241
2238,8235,1956,master,married,69245,0,1,2014-01-24,8,428,...,0,0,0,0,0,0,0,70,1,843
2239,9405,1954,phd,married,52869,1,1,2012-10-15,40,84,...,0,0,0,0,0,0,1,72,2,172

In [21]:
data.to_csv('../data/processed/dataset1_clean.csv', index=False)